### ISSUE TITLE
"Change Solution's Qt Version" is unavailable.

### ISSUE THREAD

**Issue by InterstellarVoyage** [qtproject/qt-labs-vstools#13]
On the latest version, when right-clicking on the solution, there is no "Change Solution's Qt Version" option in the Qt menu. It seems that this feature has been removed.

 - Qt VS Tool Version 2.10.1.2
 - Visual Studio version VS2019

**Comment by kaheimri** [comment]
This feature has been removed due to the fact that it was using a hack to store the Qt version used for the whole solution. This hack has become a major obstacle to migrate project handling to the latest project format and was therefor removed. Unfortunately we will not be able to bring this functionality back.
