### ISSUE TITLE
export pri file

### ISSUE THREAD

**Issue by peerhuang** [qtproject/qt-labs-vstools#27]
I want to export pri files in the latest version, how to do it? It's OK in the classic version.

**Comment by acdemiralp** [comment]
Hello, unfortunately .pri export support has been removed since version 3.0.1.

The only way to achieve this is to revert to version 2.10.1. To do so, disable auto extension updates, uninstall version 3.0.1 and install version 2.10.1 from here: https://download.qt.io/official_releases/vsaddin/2.10.1/ .

**Comment by kaheimri** [comment]
Thank you for taking the time to provide your feedback and suggestions. We have decided to remove the feature in newer versions of the Qt VS Tools extension starting with version 3.0.0, as qmake is no longer supported in the latest version of Qt6. We appreciate your understanding and encourage you to share any other ideas you may have in the future.
